"target-version" = "py313"

[lint]

select = [
    "FAST",
    "S",
    "BLE",
    "A",
    "B",
    "LOG",
    "RET",
    "SLF",
    "ARG",
    "TC",
    "I",
    "C90",
    "PERF",
    "N",
    "E",
    "W",
    "RUF",
    "PT"
]
